### ISSUE TITLE
Perlin Noise Function

### ISSUE THREAD

**Issue by JR-465856** [JR-465856/revertia-js#5]
Those who played World of Revertia saw the same map over and over again. We can solve this problem with procedural terrain generation! First things first, we need a perlin noise function.

![image](https://user-images.githubusercontent.com/97478088/233192389-0820be5c-d66f-4f86-992f-905ffc604b4b.png)
Revertia-JS could also sacrifice uncertainty for simplicity by using the sine function in lieu of perlin noise.

**Comment by 4498Lincoln** [comment]
Backtracking on this, terrain generation would complicate things much more than we need to
